services:
  - type: web
    name: latte-art-classifier
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /api/health
